# Schema for the configuration files of the ЭНЦ добмен данными с МИС module.
enc_mis.settings:
  type: config_object
  label: 'Обмен данными с МИС settings'
  mapping:
    example:
      type: string
      label: 'Example'

enc_mis.slot_filter_settings:
  type: config_object
  label: 'Enc mis filters'
  mapping:
    filters:
      type: object
      label: 'Filters'
