<?php

use Drupal\Core\Render\Element;

/**
 * Implements hook_preprocess_hook().
 */
function demo_layouts_preprocess_tabs(&$vars) {
  $tabs = [];
  $labels = $vars['layout']->getRegions();

  foreach (Element::children($vars['content']) as $ix => $region) {
    if ($ix > 0) {
      $active = !isset($active) ? 1 : $active;
      $tabs[] = [
        'id' => preg_replace('/[^a-z0-9_]+/', '_', mb_strtolower($labels[$region]['label'])),
        'title' => $labels[$region]['label'],
        'content' => $vars['content'][$region],
        'region' => $region,
        'active' => $active,
      ];
      $active = FALSE;
    }
  }

  $vars['tabs'] = $tabs;
}
