<?php

use Drupal\Component\Serialization\Json;

/**
 * @file
 * Primary module hooks for ЭНЦ добмен данными с МИС module.
 */

 /**
  * Implements hook_cron().
  */
function med_mis_cron() {
  $interval = 60 * 60 * 24;
  $next_execution = \Drupal::state()->get('med_mis_cron.holidays_next_execution', 0);
  $request_time = \Drupal::time()->getRequestTime();

  // if ($request_time >= $next_execution) {
    \Drupal::state()->set('med_mis_cron.holidays_next_execution', $request_time + $interval);

    $holidays = _med_mis_get_holidays();

    if (!empty($holidays)) {
      \Drupal::state()->set('med_holidays', $holidays);
    }
  // }
}

/**
 * Get production calendar of russia.
 */
function _med_mis_get_holidays() {
  $holidays = [];
  $year = date('Y');

  $url = "https://xmlcalendar.ru/data/ru/{$year}/calendar.json";

  $response = \Drupal::httpClient()->get($url);
  $response_body = $response->getBody();
  $result = Json::decode($response_body);

  foreach($result['months'] as $month) {
    $month_num = $month['month'] < 10 ? '0' . $month['month'] : $month['month'];
    $month_days = explode(',', $month['days']);

    foreach($month_days as $day) {
      $day = intval($day);
      $day = $day < 10 ? '0' . $day : $day;

      $holidays[] = date('Y-m-d', strtotime($year . '-' . $month_num . '-' .  $day));
    }
  }

  return $holidays;
}
